<?php

//Merchant OnBoarding Status

define('SIGN_UP_ONBOARDING',1);
define('BUSSINESS_INFO_UPDATED_ONBOARDING',2);
define('DOCUMENT_UPLOADED_ONBOARDING',3);
define('SENT_FOR_CORRECTION_ONBOARDING',4);
define('VERIFIED_ONBOARDING',5);
define('REJECTED_ONBOARDING',6);
define('CORRECTION_UPDATED_ONBOARDING',7);
define('CORRECTION_VERIFIED_ONBOARDING',8);
define('ESIGN_DOCUMENT_PENDING_ONBOARDING',9);
define('ESIGN_PENDING_ONBOARDING',10);
define('ESIGN_REJECTED_ONBOARDING',11);
define('ESIGN_DONE_ONBOARDING',12);


//Merchant Account Status
define('IN_PROCESS_ACCOUNT',1);
define('ACTIVE_ACCOUNT',2);
define('IN_ACTIVE_ACCOUNT',3);
define('SUSPENDED_ACCOUNT',4);
define('SETTLEMENT_ON_HOLD_ACCOUNT',5);


?>